### ISSUE TITLE
Linux部署Django显示未安装

### ISSUE THREAD

**Issue by senwang2016** [qq547276542/Agriculture_KnowledgeGraph#72]
`                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"`
我已经安装了django，请问应该怎么设置虚拟环境？

**Comment by zihao-miao** [comment]
> ` "Couldn't import Django. Are you sure it's installed and " "available on your PYTHONPATH environment variable? Did you " "forget to activate a virtual environment?"`
> 我已经安装了django，请问应该怎么设置虚拟环境？
> 
> 另外，我在执行`sudo sh django_server_start.sh`时还出现了另一个问题
> `Exception in thread django-main-thread: Traceback (most recent call last): File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner self.run() File "/usr/lib/python3.5/threading.py", line 862, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 54, in wrapper fn(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run self.check(display_num_errors=True) File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 390, in check include_deployment_checks=include_deployment_checks, File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 377, in _run_checks return checks.run_checks(**kwargs) File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 72, in run_checks new_errors = check(app_configs=app_configs) File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique all_namespaces = _load_all_namespaces(resolver) File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces url_patterns = getattr(resolver, 'url_patterns', []) File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__ res = instance.__dict__[self.name] = self.func(instance) File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 584, in url_patterns patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module) File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__ res = instance.__dict__[self.name] = self.func(instance) File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 577, in urlconf_module return import_module(self.urlconf_name) File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 986, in _gcd_import File "<frozen importlib._bootstrap>", line 969, in _find_and_load File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 673, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 673, in exec_module File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed File "/home/admin/newenv/demo/demo/urls.py", line 2, in <module> from . import index_view,index_ERform_view,detail_view File "/home/admin/newenv/demo/demo/index_ERform_view.py", line 7, in <module> from toolkit.pre_load import pre_load_thu,neo_con,predict_labels File "/home/admin/newenv/demo/toolkit/pre_load.py", line 13, in <module> pre_load_thu = thulac.thulac() #默认模式 File "/usr/local/lib/python3.5/dist-packages/thulac/__init__.py", line 63, in __init__ self.__tagging_decoder.init((self.__prefix+"model_c_model.bin"),(self.__prefix+"model_c_dat.bin"),(self.__prefix+"model_c_label.txt")) File "/usr/local/lib/python3.5/dist-packages/thulac/character/CBTaggingDecoder.py", line 36, in init self.model = CBModel(modelFile) File "/usr/local/lib/python3.5/dist-packages/thulac/character/CBModel.py", line 56, in __init__ temp = inputfile.read(4 * self.f_size * self.l_size) MemoryError`
用activate kg 激活你的虚拟环境

**Comment by Kyrie-LiuX** [comment]
I have the same problem ,can you help me?
